CREATE TABLE USERS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FNAME CHAR(50) DEFAULT NULL,
    LNAME CHAR(50) DEFAULT NULL,
    RFID  CHAR(200) UNIQUE NOT NULL
);

INSERT INTO USERS (FNAME, LNAME, RFID)
VALUES ( 'Mert', 'Erdemir', '1234567890' );

INSERT INTO USERS (FNAME, LNAME, RFID)
VALUES ( 'Ege', 'Ciklabakkal', '0123456789');

INSERT INTO USERS (FNAME, LNAME, RFID)
VALUES ( 'Ataberk', 'Donmez', '01234567899');

INSERT INTO USERS (FNAME, LNAME, RFID)
VALUES ( 'Mert Kaan', 'Yilmaz', '012345678990');
